version: 0.1

phases:
  build:
    commands:
      - apt-get upgrade
      - apt-get update
      - apt-get install docker-compose
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker-compose build
